/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface MyContentBundle {}
  interface MyContentBundleAttributes extends StencilHTMLAttributes {}

  interface MyDescription {}
  interface MyDescriptionAttributes extends StencilHTMLAttributes {}

  interface MyHeader {}
  interface MyHeaderAttributes extends StencilHTMLAttributes {}

  interface MyTabs {}
  interface MyTabsAttributes extends StencilHTMLAttributes {
    'onTabToggle'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyContentBundle': Components.MyContentBundle;
    'MyDescription': Components.MyDescription;
    'MyHeader': Components.MyHeader;
    'MyTabs': Components.MyTabs;
  }

  interface StencilIntrinsicElements {
    'my-content-bundle': Components.MyContentBundleAttributes;
    'my-description': Components.MyDescriptionAttributes;
    'my-header': Components.MyHeaderAttributes;
    'my-tabs': Components.MyTabsAttributes;
  }


  interface HTMLMyContentBundleElement extends Components.MyContentBundle, HTMLStencilElement {}
  var HTMLMyContentBundleElement: {
    prototype: HTMLMyContentBundleElement;
    new (): HTMLMyContentBundleElement;
  };

  interface HTMLMyDescriptionElement extends Components.MyDescription, HTMLStencilElement {}
  var HTMLMyDescriptionElement: {
    prototype: HTMLMyDescriptionElement;
    new (): HTMLMyDescriptionElement;
  };

  interface HTMLMyHeaderElement extends Components.MyHeader, HTMLStencilElement {}
  var HTMLMyHeaderElement: {
    prototype: HTMLMyHeaderElement;
    new (): HTMLMyHeaderElement;
  };

  interface HTMLMyTabsElement extends Components.MyTabs, HTMLStencilElement {}
  var HTMLMyTabsElement: {
    prototype: HTMLMyTabsElement;
    new (): HTMLMyTabsElement;
  };

  interface HTMLElementTagNameMap {
    'my-content-bundle': HTMLMyContentBundleElement
    'my-description': HTMLMyDescriptionElement
    'my-header': HTMLMyHeaderElement
    'my-tabs': HTMLMyTabsElement
  }

  interface ElementTagNameMap {
    'my-content-bundle': HTMLMyContentBundleElement;
    'my-description': HTMLMyDescriptionElement;
    'my-header': HTMLMyHeaderElement;
    'my-tabs': HTMLMyTabsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
